[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = dio_qspi
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_OV2640_SUPPORT=1
    -DCONFIG_OV3660_SUPPORT=1
    -DCONFIG_OV5640_SUPPORT=1
    -DCONFIG_OV7725_SUPPORT=1
    -DCONFIG_OV7670_SUPPORT=1
    -DCONFIG_GC2145_SUPPORT=1
    -DCONFIG_GC032A_SUPPORT=1
lib_deps =
    bblanchon/ArduinoJson@^7.2.0
